// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoxgbikjmevyfgmxsjyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFveGdiaWtqbWV2eWZnbXhzanloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzU1MDIsImV4cCI6MjA2MzQxMTUwMn0.rZxjzY0n8oYlckpbiQbFLSOPy-9rQnLjPYIPE2hPXDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);